import React, { createContext, useContext, useState, useEffect } from "react";
import axios from 'axios';

const TileSimulatorContext = createContext();

const API_URL = 'https://live-backend-3.onrender.com';

// Sample tiles with mask data
const tileCollections = {
  "Pattern Collection": [
    {
      id: 1,
      name: "BARS",
      image: "/Images/tiles/Tile-11.png",
      shape: "square",
      grout: "cross",
      scale: 1,
      colorsUsed: ["#1f1d1b", "#151312", "#c5a7b1", "#91897e", "#d2c4af"],
      masks: [
        {
          id: "mask1",
          name: "Mask Pattern 1",
          image: "/Images/tiles/masks/Mask-1.png",
          color: "#1f1d1b",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
        {
          id: "mask2",
          name: "Mask Pattern 2",
          image: "/Images/tiles/masks/Mask-2.png",
          color: "#151312",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
        {
          id: "mask3",
          name: "Mask Pattern 3",
          image: "/Images/tiles/masks/Mask-3.png",
          color: "#c5a7b1",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
        {
          id: "mask4",
          name: "Mask Pattern 4",
          image: "/Images/tiles/masks/Mask-4.png",
          color: "#91897e",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
        {
          id: "mask5",
          name: "Mask Pattern 5",
          image: "/Images/tiles/masks/Mask-5.png",
          color: "#d2c4af",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
      ],
    },
  ],
  "Hexagon Collection": [
    {
      id: 2,
      name: "HEX ONE",
      image: "/Images/tiles/hex1.jpg",
      shape: "hexagon",
      grout: "hex",
      scale: 1,
      colorsUsed: ["#4299E1", "#EBF8FF", "#63B3ED", "#3182CE", "#2B6CB0"],
      masks: [
        {
          id: "mask1",
          name: "Hex Pattern",
          image: "/Images/tiles/masks/hex-mask-1.png",
          color: "#4299E1",
          availableColors: [
            "#4299E1",
            "#3182CE",
            "#2B6CB0",
            "#2C5282",
            "#2A4365",
            "#1A365D",
          ],
        },
        {
          id: "mask2",
          name: "Background",
          image: "/Images/tiles/masks/hex-mask-2.png",
          color: "#EBF8FF",
          availableColors: [
            "#EBF8FF",
            "#BEE3F8",
            "#90CDF4",
            "#63B3ED",
            "#4299E1",
            "#3182CE",
          ],
        },
      ],
    },
    {
      id: 3,
      name: "HEX TWO",
      image: "/Images/tiles/hex2.jpg",
      shape: "hexagon",
      grout: "hex",
      scale: 1,
      colorsUsed: ["#ED8936", "#FEEBC8", "#F6AD55", "#DD6B20", "#C05621"],
      masks: [
        {
          id: "mask1",
          name: "Hex Pattern",
          image: "/Images/tiles/masks/hex-mask-3.png",
          color: "#ED8936",
          availableColors: [
            "#ED8936",
            "#DD6B20",
            "#C05621",
            "#9C4221",
            "#7B341E",
            "#652B19",
          ],
        },
        {
          id: "mask2",
          name: "Background",
          image: "/Images/tiles/masks/hex-mask-4.png",
          color: "#FEEBC8",
          availableColors: [
            "#FEEBC8",
            "#FBD38D",
            "#F6AD55",
            "#ED8936",
            "#DD6B20",
            "#C05621",
          ],
        },
      ],
    },
  ],
  "Elite Collection": [
    {
      id: 4,
      name: "ELITE A",
      image: "/Images/tiles/elitea.jpg",
      shape: "square",
      grout: "cross",
      scale: 1,
      colorsUsed: ["#2D3748", "#E2E8F0", "#A0AEC0", "#4A5568", "#2D3748"],
      masks: [
        {
          id: "mask1",
          name: "Elite Pattern",
          image: "/Images/tiles/masks/elite-mask-1.png",
          color: "#2D3748",
          availableColors: [
            "#2D3748",
            "#1A202C",
            "#171923",
            "#2D3748",
            "#4A5568",
            "#718096",
          ],
        },
        {
          id: "mask2",
          name: "Accent",
          image: "/Images/tiles/masks/elite-mask-2.png",
          color: "#E2E8F0",
          availableColors: [
            "#E2E8F0",
            "#CBD5E0",
            "#A0AEC0",
            "#718096",
            "#4A5568",
            "#2D3748",
          ],
        },
      ],
    },
    {
      id: 5,
      name: "ELITE B",
      image: "/Images/tiles/eliteb.jpg",
      shape: "square",
      grout: "cross",
      scale: 1,
      colorsUsed: ["#1A202C", "#F7FAFC", "#A0AEC0", "#4A5568", "#2D3748"],
      masks: [
        {
          id: "mask1",
          name: "Elite Pattern",
          image: "/Images/tiles/masks/elite-mask-3.png",
          color: "#1A202C",
          availableColors: [
            "#1A202C",
            "#171923",
            "#2D3748",
            "#4A5568",
            "#718096",
            "#A0AEC0",
          ],
        },
        {
          id: "mask2",
          name: "Background",
          image: "/Images/tiles/masks/elite-mask-4.png",
          color: "#F7FAFC",
          availableColors: [
            "#F7FAFC",
            "#EDF2F7",
            "#E2E8F0",
            "#CBD5E0",
            "#A0AEC0",
            "#718096",
          ],
        },
      ],
    },
  ],
  "Border Collection": [
    {
      id: 6,
      name: "BORDER A",
      image: "/Images/borders/Main-Border.png",
      shape: "rectangle",
      grout: "line",
      scale: 1,
      colorsUsed: [
        "#584a49",
        "#9e867a",
        "#5a4b48",
        "#ffffff",
        "#5a4b48",
        "#584a49",
        "#9a8073",
        "#bccacd",
      ],
      masks: [
        {
          maskId: "mask1",
          name: "Border Mask 1",
          image: "/Images/borders/bordersmask/Border1.png",
          color: "#584a49",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
        {
          maskId: "mask2",
          name: "Border Mask 2",
          image: "/Images/borders/bordersmask/Border2.png",
          color: "#9e867a",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
        {
          maskId: "mask3",
          name: "Border Mask 3",
          image: "/Images/borders/bordersmask/Border3.png",
          color: "#5a4b48",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
        {
          maskId: "mask4",
          name: "Border Mask 4",
          image: "/Images/borders/bordersmask/Border4.png",
          color: "#ffffff",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
        {
          maskId: "mask5",
          name: "Border Mask 5",
          image: "/Images/borders/bordersmask/Border5.png",
          color: "#5a4b48",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
        {
          maskId: "mask6",
          name: "Border Mask 6",
          image: "/Images/borders/bordersmask/Border6.png",
          color: "#584a49",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
        {
          maskId: "mask7",
          name: "Border Mask 7",
          image: "/Images/borders/bordersmask/Border7.png",
          color: "#9a8073",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
        {
          maskId: "mask8",
          name: "Border Mask 8",
          image: "/Images/borders/bordersmask/Border8.png",
          color: "#bccacd",
          availableColors: [
            "#0D1117",
            "#1C1C1E",
            "#2D3748",
            "#1A202C",
            "#202124",
            "#171923",
            "#4A5568",
            "#5C6370",
            "#718096",
            "#A0AEC0",
            "#CBD5E0",
            "#E2E8F0",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#FF6B6B",
            "#FFB300",
            "#00B894",
            "#00BFFF",
            "#FFD700",
            "#FF00FF",
            "#7D5FFF",
            "#1ABC9C",
            "#F39C12",
            "#E91E63",
            "#74B9FF",
            "#55EFC4",
            "#81ECEC",
            "#A29BFE",
            "#FFFFFF",
            "#000000",
            "#F5F5F5",
            "#2C3E50",
            "#ECF0F1",
          ],
        },
      ],
    },
  ],
};

export const TileSimulatorProvider = ({ children }) => {
  const [tileCollections, setTileCollections] = useState({});
  const [selectedCategory, setSelectedCategory] = useState("Pattern Collection");
  const [selectedBorder, setSelectedBorder] = useState(null);
  const [selectedSize, setSelectedSize] = useState(() => {
    const savedSize = localStorage.getItem("selectedSize");
    return savedSize || "8x8";
  });
  const [selectedEnvironment, setSelectedEnvironment] = useState("bedroom");
  const [groutColor, setGroutColor] = useState("#f5f5f5");
  const [groutThickness, setGroutThickness] = useState("none");
  const [selectedTile, setSelectedTile] = useState(() => {
    const savedTile = localStorage.getItem("selectedTile");
    return savedTile ? JSON.parse(savedTile) : null;
  });
  const [selectedColor, setSelectedColor] = useState(() => {
    const savedColor = localStorage.getItem("selectedColor");
    return savedColor || null;
  });
  const [tileMasks, setTileMasks] = useState([]);
  const [borderMasks, setBorderMasks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchTiles = async () => {
      try {
        console.log('Fetching tiles from:', `${API_URL}/api/tiles`);
        const response = await axios.get(`${API_URL}/api/tiles`);
        console.log('API Response:', response.data);

        if (!response.data || !Array.isArray(response.data)) {
          throw new Error('Invalid API response format');
        }

        const transformedTiles = {
          "Pattern Collection": response.data.map(tile => {
            console.log('Processing tile:', tile);
            return {
              id: tile._id,
              name: tile.tileName || tile.name,
              image: tile.mainMask || tile.image,
              shape: tile.shape || "square",
              grout: tile.grout || "cross",
              scale: tile.scale || 1,
              colorsUsed: tile.colorsUsed || ["#ffffff"],
              masks: (tile.masks || []).map(mask => ({
                ...mask,
                image: mask.image || mask.maskImage
              }))
            };
          })
        };

        console.log('Transformed tiles:', transformedTiles);
        setTileCollections(transformedTiles);
      } catch (error) {
        console.error('Error fetching tiles:', error);
        console.error('Error details:', {
          message: error.message,
          response: error.response?.data,
          status: error.response?.status
        });
        setError(error.response?.data?.error || error.message || "Failed to fetch tiles");
      } finally {
        setLoading(false);
      }
    };

    fetchTiles();
  }, []);

  const handleTileSelect = (tile) => {
    setSelectedTile(tile);
    localStorage.setItem("selectedTile", JSON.stringify(tile));
  };

  const setTileMaskColor = (maskId, color) => {
    setTileMasks(prevMasks =>
      prevMasks.map(mask =>
        mask.id === maskId ? { ...mask, color } : mask
      )
    );
  };

  const handleBorderSelect = (border) => {
    setSelectedBorder(border);
  };

  const setBorderMaskColor = (maskId, color) => {
    setBorderMasks(prevMasks =>
      prevMasks.map(mask =>
        mask.id === maskId ? { ...mask, color } : mask
      )
    );
  };

  const value = {
    tileCollections,
    selectedCategory,
    setSelectedCategory,
    selectedBorder,
    setSelectedBorder,
    selectedSize,
    setSelectedSize,
    selectedEnvironment,
    setSelectedEnvironment,
    groutColor,
    setGroutColor,
    groutThickness,
    setGroutThickness,
    selectedTile,
    setSelectedTile: handleTileSelect,
    tileMasks,
    setTileMaskColor,
    borderMasks,
    setBorderMaskColor,
    loading,
    error
  };

  return (
    <TileSimulatorContext.Provider value={value}>
      {children}
    </TileSimulatorContext.Provider>
  );
};

export const useTileSimulator = () => {
  const context = useContext(TileSimulatorContext);
  if (!context) {
    throw new Error("useTileSimulator must be used within a TileSimulatorProvider");
  }
  return context;
};
